spring.application.name=plant-control-api

#postgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/plant_control_db
spring.datasource.username=postgres
spring.datasource.password=1234

app.jwt.secret=plant-control-secret-key-for-development-please-change-this-value-later
app.jwt.expiration-ms=86400000

#JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#postgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#server port
server.port=8080
